# -*- coding: utf-8 -*-
"""diabetes dash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sdOI1F54aMz1BleRs_njA8dNphxXQRZw
"""

import webbrowser

linkedin_url = "www.linkedin.com/in/hassan-saleh-999a86157"

import base64

main_bg = "sample2.jpg"
main_bg_ext = "jpg"

from PIL import Image

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import plotly.express as px
matplotlib.use("Agg")
import joblib
import os
import pickle

from random import choices
import streamlit as st
from streamlit_option_menu import option_menu
from eda_app import run_eda_app
from ml_app import run_ml_app

st.set_page_config(page_title="Early Diabetes Risk Prediction",
                        page_icon="🦍")

st.markdown(
    f"""
    <style>
    .reportview-container {{
        background: url(data:image/{main_bg_ext};base64,{base64.b64encode(open(main_bg, "rb").read()).decode()})
    }}
   
    </style>
    """,
    unsafe_allow_html=True
)


def main():
  selected = option_menu(
      menu_title= None,
      options=["Home","EDA","ML Model","About"],
      icons=["house","book","envelope","person lines fill"],
      menu_icon="app-indicator", default_index=0,
                         styles={
        "container": {"padding": "5!important", "background-color": "#fafafa"},
        "icon": {"color": "orange", "font-size": "25px"}, 
        "nav-link": {"font-size": "16px", "text-align": "left", "margin":"0px", "--hover-color": "#eee"},
        "nav-link-selected": {"background-color": "#02ab21"}},
      orientation="horizontal"
  )
  if selected=="Home":
        st.title("Early Diabetes Risk Prediction Dashboard")
        st.write("""
			Diabetes mellitus, commonly known as diabetes, is a **metabolic disease** that causes **high blood sugar**.
        The hormone insulin moves sugar from the blood into your cells to be stored or used for energy.
        With diabetes, your body either **doesn’t make enough insulin** or **can’t effectively use the insulin it does make**. 
        
        By: Hassan Saleh
			""")
        pass
  elif selected=="EDA":
        run_eda_app()

        pass
  elif selected=="ML Model":
        run_ml_app()
        pass
  else:
        st.title("About")
        image = Image.open('hassan1.jpg')
        st.image(image,use_column_width=True)
        st.subheader("About Me 👨‍🎓")
        st.text("Hi, I am Hassan. I am a data science who Helps people Create The change that Matters, and willing to change my ambitions to Reality, Pharmacist with demonstrated history of working in the pharmaceutical industry. Health Care and data analytics Enthusiast.")
        st.text("I take avid interests in breaking down complex problems and leverage data to drive business")
        if st.button("Linkedin 🔗"):
            webbrowser.open_new_tab(linkedin_url)

    
if __name__=="__main__":
    main()

